#!/usr/bin/env python3

import sys
import os
import helpers

from analyzer import Analyzer
from termcolor import colored

def main():
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets screenname")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    screenName = sys.argv[1]
    tweets = helpers.get_user_timeline(screenName, 50)

    if tweets == None:
        sys.exit("Error occurred when fetching {}'s tweets (possibly an invalid screenname, or the user has their tweets set to private".format(screenName))

    for tweet in tweets:
        score = analyzer.analyze(tweet)
        print(sentiment_colored_text("{} {}".format(score, tweet), score))

def sentiment_colored_text(text, score):
    if score > 0.0:
        return colored(text, "green")
    elif score < 0.0:
        return colored(text, "red")
    else:
        return colored(text, "yellow")

if __name__ == "__main__":
    main()
